---
title: "`grateful` citation report"
bibliography: grateful-refs.bib
#csl: null.csl
---

## R packages used

|Package           |Version  |Citation                                                                            |
|:-----------------|:--------|:-----------------------------------------------------------------------------------|
|arsenal           |3.6.3    |@arsenal                                                                            |
|base              |4.4.1    |@base                                                                               |
|BiocManager       |1.30.23  |@BiocManager                                                                        |
|cluster           |2.1.6    |@cluster                                                                            |
|clustertend       |1.7      |@clustertend                                                                        |
|corrplot          |0.92     |@corrplot2021                                                                       |
|data.table        |1.15.4   |@datatable                                                                          |
|DataExplorer      |0.8.3    |@DataExplorer                                                                       |
|devtools          |2.4.5    |@devtools                                                                           |
|dlookr            |0.6.3    |@dlookr                                                                             |
|factoextra        |1.0.7    |@factoextra                                                                         |
|FeatureImpCluster |0.1.5    |@FeatureImpCluster                                                                  |
|flexclust         |1.4.2    |@flexclust2006a; @flexclust2006c; @flexclust2006d; @flexclust2010b; @flexclust2018e |
|flextable         |0.9.6    |@flextable                                                                          |
|fpc               |2.2.12   |@fpc                                                                                |
|GGally            |2.2.1    |@GGally                                                                             |
|ggrepel           |0.9.5    |@ggrepel                                                                            |
|ggside            |0.3.1    |@ggside                                                                             |
|ggstatsplot       |0.12.4   |@ggstatsplot                                                                        |
|here              |1.0.1    |@here                                                                               |
|Hmisc             |5.1.3    |@Hmisc                                                                              |
|kableExtra        |1.4.0    |@kableExtra                                                                         |
|mice              |3.16.0   |@mice                                                                               |
|moments           |0.14.1   |@moments                                                                            |
|naniar            |1.1.0    |@naniar                                                                             |
|NbClust           |3.0.1    |@NbClust                                                                            |
|performance       |0.12.2   |@performance                                                                        |
|psych             |2.4.6.26 |@psych                                                                              |
|recipes           |1.1.0    |@recipes                                                                            |
|rmarkdown         |2.27     |@rmarkdown2018; @rmarkdown2020; @rmarkdown2024                                      |
|SmartEDA          |0.3.10   |@SmartEDA                                                                           |
|summarytools      |1.0.1    |@summarytools                                                                       |
|tidyverse         |2.0.0    |@tidyverse                                                                          |

**You can paste this paragraph directly in your report:**

We used R version 4.4.1 [@base] and the following R packages: arsenal v. 3.6.3 [@arsenal], BiocManager v. 1.30.23 [@BiocManager], cluster v. 2.1.6 [@cluster], clustertend v. 1.7 [@clustertend], corrplot v. 0.92 [@corrplot2021], data.table v. 1.15.4 [@datatable], DataExplorer v. 0.8.3 [@DataExplorer], devtools v. 2.4.5 [@devtools], dlookr v. 0.6.3 [@dlookr], factoextra v. 1.0.7 [@factoextra], FeatureImpCluster v. 0.1.5 [@FeatureImpCluster], flexclust v. 1.4.2 [@flexclust2006a; @flexclust2006c; @flexclust2006d; @flexclust2010b; @flexclust2018e], flextable v. 0.9.6 [@flextable], fpc v. 2.2.12 [@fpc], GGally v. 2.2.1 [@GGally], ggrepel v. 0.9.5 [@ggrepel], ggside v. 0.3.1 [@ggside], ggstatsplot v. 0.12.4 [@ggstatsplot], here v. 1.0.1 [@here], Hmisc v. 5.1.3 [@Hmisc], kableExtra v. 1.4.0 [@kableExtra], mice v. 3.16.0 [@mice], moments v. 0.14.1 [@moments], naniar v. 1.1.0 [@naniar], NbClust v. 3.0.1 [@NbClust], performance v. 0.12.2 [@performance], psych v. 2.4.6.26 [@psych], recipes v. 1.1.0 [@recipes], rmarkdown v. 2.27 [@rmarkdown2018; @rmarkdown2020; @rmarkdown2024], SmartEDA v. 0.3.10 [@SmartEDA], summarytools v. 1.0.1 [@summarytools], tidyverse v. 2.0.0 [@tidyverse].

## Package citations

