toc-title-document: "Tabla de contenidos"
toc-title-website: "En esta página"

related-formats-title: "Otros formatos"
related-notebooks-title: "Notebooks"
source-notebooks-prefix: "Source"
other-links-title: "Otros enlaces"
code-links-title: "Enlaces al código"
launch-dev-container-title: "Launch Dev Container"
launch-binder-title: "Launch Binder"

article-notebook-label: "Article Notebook"
notebook-preview-download: "Descargar Notebook"
notebook-preview-download-src: "Descargar código fuente"
notebook-preview-back: "Volver al artículo"
manuscript-meca-bundle: "MECA Bundle"

section-title-abstract: "Resumen"
section-title-appendices: "Apéndices"
section-title-footnotes: "Notas al pie"
section-title-references: "Referencias"
section-title-reuse: "Reutilizar"
section-title-copyright: "Copyright"
section-title-citation: "Cita"

appendix-attribution-cite-as: "Para atribución, se ruega citar este trabajo como:"
appendix-attribution-bibtex: "Cita BibTeX:"

title-block-author-single: "Autor"
title-block-author-plural: "Autores"
title-block-affiliation-single: "Afiliación"
title-block-affiliation-plural: "Afiliaciones"
title-block-published: "Fecha publicación"
title-block-modified: "Modificado"
title-block-keywords: "Palabras clave"

callout-tip-title: "Consejo"
callout-note-title: "Nota"
callout-warning-title: "Aviso"
callout-important-title: "Importante"
callout-caution-title: "Precaución"

code-summary: "Código"

code-tools-menu-caption: "Código"
code-tools-show-all-code: "Mostrar todo el código"
code-tools-hide-all-code: "Ocultar todo el código"
code-tools-view-source: "View Source"
code-tools-source-code: "Source Code"

code-line: "Línea"
code-lines: "Líneas"

copy-button-tooltip: "Copiar al portapapeles"
copy-button-tooltip-success: "¡Copiado!"

repo-action-links-edit: "Editar esta página"
repo-action-links-source: "View source"
repo-action-links-issue: "Informar de una incidencia"

back-to-top: "Back to top"

search-no-results-text: "Sin resultados"
search-matching-documents-text: "matching documents"
search-copy-link-title: "Copy link to search"
search-hide-matches-text: "Hide additional matches"
search-more-match-text: "more match in this document"
search-more-matches-text: "more matches in this document"
search-clear-button-title: "Clear"
search-detached-cancel-button-title: "Cancel"
search-submit-button-title: "Submit"
search-label: "Search"

toggle-section: "Toggle section"
toggle-sidebar: "Toggle sidebar navigation"
toggle-dark-mode: "Toggle dark mode"
toggle-reader-mode: "Toggle reader mode"
toggle-navigation: "Toggle navigation"

crossref-fig-title: "Figura"
crossref-tbl-title: "Tabla"
crossref-lst-title: "Lista"
crossref-thm-title: "Teorema"
crossref-lem-title: "Lema"
crossref-cor-title: "Corolario"
crossref-prp-title: "Proposición"
crossref-cnj-title: "Conjetura"
crossref-def-title: "Definición"
crossref-exm-title: "Ejemplo"
crossref-exr-title: "Ejercicio"
crossref-ch-prefix: "Capítulo"
crossref-apx-prefix: "Apéndice"
crossref-sec-prefix: "Sección"
crossref-eq-prefix: "Ecuación"
crossref-lof-title: "Lista de figuras"
crossref-lot-title: "Lista de tablas"
crossref-lol-title: "Lista de listas"

environment-proof-title: "Prueba"
environment-remark-title: "Comentario"
environment-solution-title: "Solución"

listing-page-order-by: "Ordenar"
listing-page-order-by-default: "por defecto"
listing-page-order-by-date-asc: "desde el más antiguo"
listing-page-order-by-date-desc: "desde el más nuevo"
listing-page-order-by-number-desc: "de mayor a menor"
listing-page-order-by-number-asc: "de menor a mayor"
listing-page-field-date: "Fecha"
listing-page-field-title: "Título"
listing-page-field-description: "Descripción"
listing-page-field-author: "Autor"
listing-page-field-filename: "Nombre de archivo"
listing-page-field-filemodified: "Modificado"
listing-page-field-subtitle: "Subtítulo"
listing-page-field-readingtime: "Tiempo de lectura"
listing-page-field-wordcount: "Recuento de palabras"
listing-page-field-categories: "Categorias"
listing-page-minutes-compact: "{0} min"
listing-page-category-all: "Todo"
listing-page-no-matches: "No hay coincidencias"
listing-page-words: "{0} palabras"
